project_id = "nsvwbqvnjsixepxrxysd"

[functions.sync-exchange-rates]
verify_jwt = false

[functions.initialize-payment]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.send-sms]
verify_jwt = false

[functions.send-whatsapp]
verify_jwt = false

[functions.due-date-reminders]
verify_jwt = false

[functions.initialize-registration-payment]
verify_jwt = false

[functions.verify-registration-payment]
verify_jwt = false

[functions.initialize-measurement-payment]
verify_jwt = false

[functions.verify-measurement-payment]
verify_jwt = false

[functions.ai-measure-detect]
verify_jwt = false

[functions.notify-admin-registration]
verify_jwt = false

[functions.twilio-webhook]
verify_jwt = false
